"""
Locust load-testing script for Event Booking System.

Focuses primarily on concurrent customers booking the SAME high-capacity event (hot path).
Uses pre-generated customer tokens from locust/test_config.json to accurately measure
database row locking, transaction duration, and API connection pool concurrency.
"""
import json
import os
import random
from locust import HttpUser, between, task

# Load test configuration generated by setup_test_data.py
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "test_config.json")
EVENT_ID = None
TOKENS = []

if os.path.exists(CONFIG_PATH):
    with open(CONFIG_PATH, "r") as f:
        _cfg = json.load(f)
        EVENT_ID = _cfg.get("event_id")
        TOKENS = _cfg.get("customer_tokens", [])


class ConcurrentBookingUser(HttpUser):
    """
    Simulates a concurrent customer booking tickets on the shared event.
    """
    wait_time = between(0.1, 0.5)

    def on_start(self):
        config = _cfg if os.path.exists(CONFIG_PATH) else {}
        if os.environ.get("LOAD_TEST_USE_PREISSUED_TOKENS") == "1" and TOKENS:
            self.token = random.choice(TOKENS)
        else:
            customer_email = config.get("customer_email", "perf_customer_1@example.com")
            customer_password = config.get("customer_password", "password123")
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": customer_email, "password": customer_password},
                name="/api/v1/auth/login [POST]",
            )
            login_response.raise_for_status()
            self.token = login_response.json()["access_token"]
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }
        self.event_id = EVENT_ID

    @task(8)
    def book_ticket_on_shared_event(self):
        """Hot path: book ticket on the shared event row."""
        if not self.event_id:
            return

        payload = {
            "event_id": self.event_id,
            "quantity": 1,
        }
        with self.client.post(
            "/api/v1/bookings/",
            headers=self.headers,
            json=payload,
            catch_response=True,
            name="/api/v1/bookings/ [POST]",
        ) as response:
            if response.status_code == 201:
                response.success()
            elif response.status_code == 409:
                # Keep expected contention visible in Locust failure metrics.
                response.failure("HTTP 409 Conflict")
            else:
                response.failure(f"HTTP {response.status_code}: {response.text[:100]}")

    @task(2)
    def view_event_detail(self):
        """Read path: view event details."""
        if not self.event_id:
            return
        self.client.get(
            f"/api/v1/events/{self.event_id}",
            name="/api/v1/events/{id} [GET]",
        )

    @task(1)
    def browse_published_events(self):
        """Exercise the public event browsing and filtering path."""
        self.client.get(
            "/api/v1/events/?page=1&size=20",
            name="/api/v1/events/ [GET]",
        )


class OrganizerEventUser(HttpUser):
    """Exercises organizer login plus event creation and update workflows."""
    weight = 0
    wait_time = between(1, 3)

    def on_start(self):
        config = _cfg if os.path.exists(CONFIG_PATH) else {}
        response = self.client.post(
            "/api/v1/auth/login",
            json={
                "email": config.get("organizer_email", "loadtest_organizer@example.com"),
                "password": config.get("organizer_password", "password123"),
            },
            name="/api/v1/auth/login [POST] organizer",
        )
        response.raise_for_status()
        self.headers = {
            "Authorization": f"Bearer {response.json()['access_token']}",
            "Content-Type": "application/json",
        }
        self.event_id = None

    @task
    def create_and_update_event(self):
        """Exercise organizer event creation followed by an owned update."""
        from datetime import datetime, timedelta, timezone

        now = datetime.now(timezone.utc)
        response = self.client.post(
            "/api/v1/events/",
            headers=self.headers,
            json={
                "title": f"Load Test Event {random.randint(1, 1_000_000)}",
                "starts_at": (now + timedelta(days=5)).isoformat(),
                "ends_at": (now + timedelta(days=5, hours=2)).isoformat(),
                "total_tickets": 1000,
                "price_cents": 2500,
            },
            name="/api/v1/events/ [POST] organizer",
        )
        if response.status_code != 201:
            response.failure(f"HTTP {response.status_code}: {response.text[:100]}")
            return
        event_id = response.json()["id"]
        self.client.patch(
            f"/api/v1/events/{event_id}",
            headers=self.headers,
            json={"title": "Updated Load Test Event"},
            name="/api/v1/events/{id} [PATCH] organizer",
        )
